#                                              Array

In [1]:
import numpy as np
a = (1,2,3,4,5)
print(a)
b = np.array(a)
print(b)
b

(1, 2, 3, 4, 5)
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

### Multiple lists

In [2]:
aa = [2,3,5],[456] 
aa

([2, 3, 5], [456])

In [3]:
import numpy as np
bb = np.array([[1,2,3] , [5,6,7]])
bb

array([[1, 2, 3],
       [5, 6, 7]])

### Multiple Tuples

In [4]:
aa1 = (2,3,5),(456)
aa

([2, 3, 5], [456])

In [5]:
bb1 = np.array(((1,2,3) , (5,6,7)))
bb1

array([[1, 2, 3],
       [5, 6, 7]])

### Multiple Entire List using "np"

In [6]:
cc = [1,4,6,7,3],[2,5,4,2,4]
ccc = np.array(cc)
print(ccc*2)

# Without "NP" ( Wrong )
cc1 = [1,4,6,7,3],[2,5,4,2,4]
print(cc1*2)

[[ 2  8 12 14  6]
 [ 4 10  8  4  8]]
([1, 4, 6, 7, 3], [2, 5, 4, 2, 4], [1, 4, 6, 7, 3], [2, 5, 4, 2, 4])


In [7]:

a1 = [1,2,3,4,5]
b1 = np.array(a1)
print(b1)
b1

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

# Type

In [8]:
type(a)

tuple

In [9]:
type(b)

numpy.ndarray

In [10]:
type(a1)

list

In [11]:
type(b1)

numpy.ndarray

# convert list to array

In [12]:
c = [1,3,4,5,6,8]     # it is an list 
d = np.array(c)       # it is an array
d

array([1, 3, 4, 5, 6, 8])

### Changes For List ( We can modify the List )

In [13]:
c[0] = "hari"     
c

['hari', 3, 4, 5, 6, 8]

In [14]:
c[1] = 8
c

['hari', 8, 4, 5, 6, 8]

### Changes after Convert list to array

In [15]:
d[4] = 'krishna'  # It show an error 
d                 


# If we want to minimize the error means we need to convert "elements" as Srings 

# string_array = d.astype(str)
# string_array[4] = "krishna"
# string_array

ValueError: invalid literal for int() with base 10: 'krishna'

In [16]:
d[4] = 9
d

array([1, 3, 4, 5, 9, 8])

# Tuples to Array

In [17]:
z = (1 , "hari" , 3 , 2 , "perivi")
z1 = np.array(z)
z1

array(['1', 'hari', '3', '2', 'perivi'], dtype='<U11')

### Changes for Tuples ( We can't modify the Tuple )

In [18]:
z[1] = "krishna"  # Error

TypeError: 'tuple' object does not support item assignment

In [19]:
z[2] = 9  # Error

TypeError: 'tuple' object does not support item assignment

### Changes after convert Tuple to Array 

In [20]:
z1[1] = "sangeetham"
z1

array(['1', 'sangeetham', '3', '2', 'perivi'], dtype='<U11')

In [21]:
z1[2] = 100
z1

array(['1', 'sangeetham', '100', '2', 'perivi'], dtype='<U11')

# float array

### array to float

In [22]:
m = [ [1,25,4,5,67] ,
     [3,55,7,95,0] ]
n = np.array(m)
n

array([[ 1, 25,  4,  5, 67],
       [ 3, 55,  7, 95,  0]])

In [23]:
n1 = n.astype(float)
n1

array([[ 1., 25.,  4.,  5., 67.],
       [ 3., 55.,  7., 95.,  0.]])

### float to int

In [24]:
x = n.astype(int)
x

array([[ 1, 25,  4,  5, 67],
       [ 3, 55,  7, 95,  0]])

 # Boolean array

### array to boolean

In [25]:
o = [ [1,25,4,5,67] ,
     [3,55,7,-95,0] ]
p = np.array(o)
p

array([[  1,  25,   4,   5,  67],
       [  3,  55,   7, -95,   0]])

In [26]:
q = p.astype(bool)         # in bool 0 = false , any other number = 1
q

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

### bool to int

In [27]:
y = q.astype(int)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0]])