# Array Dimension

In [1]:
import numpy as np

In [4]:
list1 = [[[ [ [1.5,3,5,7,9 , 4], [2,4,6,8,2,0] , [2,4,6,8,3,0] ] , [ [1.5,3,5,7,9,5], [2,4,6,4,8,0], [2,4,6,3,8,0] ]  ]]]
array1 = np.array(list1)
array1

array([[[[[1.5, 3. , 5. , 7. , 9. , 4. ],
          [2. , 4. , 6. , 8. , 2. , 0. ],
          [2. , 4. , 6. , 8. , 3. , 0. ]],

         [[1.5, 3. , 5. , 7. , 9. , 5. ],
          [2. , 4. , 6. , 4. , 8. , 0. ],
          [2. , 4. , 6. , 3. , 8. , 0. ]]]]])

In [9]:
array1.shape     # row x column = shape

(1, 1, 2, 3, 6)

In [8]:
array1.size    # Mutliply the Shape

36

In [6]:
array1.ndim    # how many ending backets (dimensions)

5

In [10]:
array1.dtype

dtype('float64')

### 1D Array

In [11]:
import numpy as np

z = [2,8,90,5]
z = np.array(z)
print(z.ndim)

1


In [12]:
print(z[2])

90


### 2D Array

In [13]:
import numpy as np
a = [1,2,3,4,5] , [6,7,8,9,0]
a = np.array(a)
print(a)
print(a.ndim)
print(a.shape)

# or

a = [[1,2,3,4,5] , [6,7,8,9,0] , [1,2,3,4,5] , [6,7,8,9,0]]
a = np.array(a)
print(a)
print(a.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
2
(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]]
2


In [14]:
print(a[1])

[6 7 8 9 0]


In [15]:
print(a[1][2])

8


### 3D Array

In [16]:
import numpy as np

b =    [[2,3,6,7],[2,6,1,8],[3,5,7,3]]     ,   [[2,5,8,4 ],[7,3,2,1] ,[3,7,0,9]]    # More than one zip list is belongs to 3D
bb = np.array(b)
print(bb)
print(bb.shape) 
print(bb.ndim)  # It show dimension.

# or

b =    [[[2,3,6,7],[2,6,1,8],[3,5,7,3]]     ,   [[2,5,8,4 ],[7,3,2,1] ,[3,7,0,9]]]    # More than one zip list is belongs to 3D
bb = np.array(b)
print(bb)
print(bb.ndim)  # It show dimension.

[[[2 3 6 7]
  [2 6 1 8]
  [3 5 7 3]]

 [[2 5 8 4]
  [7 3 2 1]
  [3 7 0 9]]]
(2, 3, 4)
3
[[[2 3 6 7]
  [2 6 1 8]
  [3 5 7 3]]

 [[2 5 8 4]
  [7 3 2 1]
  [3 7 0 9]]]
3


In [27]:
print(bb.shape)   # It have range 2 = (0,1) , 3 = (0,1,2) , 5 = (0,1,2,3,4)

(2, 3, 4)


In [28]:
print(bb[1])

[[2 5 8 4]
 [7 3 2 1]
 [3 7 0 9]]


In [29]:
print(bb[1][2])

[3 7 0 9]


In [30]:
print(bb[1][2][3])

9


#### or


In [52]:
print(bb[1])

[[2 5 8 4]
 [7 3 2 1]
 [3 7 0 9]]


In [53]:
print(bb[1,2])

[3 7 0 9]


In [54]:
print(bb[1,2,2])

0


### Additional example

#### Ex 1

In [34]:
z = [[[[2,3,4] , [2,5,7]]] , [[[3,5,1] ,[8,9,3]]] , [[[1,6,2] ,[5,9,0]]]]
z = np.array(z)
print(z)

[[[[2 3 4]
   [2 5 7]]]


 [[[3 5 1]
   [8 9 3]]]


 [[[1 6 2]
   [5 9 0]]]]


In [37]:
print(z.shape)  # So it have 3 = (0,1,2) , 1 = (0) , 2 = (0,1) , 3 = (0,1,2)

(3, 1, 2, 3)


In [38]:
print(z[2])

[[[1 6 2]
  [5 9 0]]]


In [39]:
print(z[2][0])   # Understand this one

[[1 6 2]
 [5 9 0]]


In [40]:
print(z[2][0][1])

[5 9 0]


In [41]:
print(z[2][0][1][2])

0


### 3D Another Ex

In [42]:

b =   [[2,3,6,7,5],[2,5,6,1,8],[3,5,7,7,3]] , [[1,2,3,4,5] , [6,7,8,9,0] ,[2,3,5,1,4]] ,  [[1,2,3,4,5] , [6,7,8,9,0] , [2,4,5,2,8]]   # More than one zip list is belongs to 3D
print(b)
bb = np.array(b)
print(bb)
print(bb.shape) 
print(bb.ndim)  # It show dimension.

([[2, 3, 6, 7, 5], [2, 5, 6, 1, 8], [3, 5, 7, 7, 3]], [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 3, 5, 1, 4]], [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [2, 4, 5, 2, 8]])
[[[2 3 6 7 5]
  [2 5 6 1 8]
  [3 5 7 7 3]]

 [[1 2 3 4 5]
  [6 7 8 9 0]
  [2 3 5 1 4]]

 [[1 2 3 4 5]
  [6 7 8 9 0]
  [2 4 5 2 8]]]
(3, 3, 5)
3


In [63]:
print(bb[0][1])

[2 5 6 1 8]


### Ex

In [43]:
z = [2,3,5] , [3,3,2] , [3,2,6]
z = np.array(z)
print(z.shape)
print(z[2][2])

(3, 3)
6
