# Reversing  Rows and Columns

In [28]:
import numpy as np

### ex 1

In [29]:
a = [[1,2,3,4,5],
      [2,4,6,8,0],
      [1,3,5,7,9]] 
     
c =  np.array(a)        
c 

array([[1, 2, 3, 4, 5],
       [2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

In [30]:
c[::-1]           # it is reverse the Horizontal mirror img (original)

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0],
       [1, 2, 3, 4, 5]])

#### or

In [31]:
c[::-1,::+1]       # it is reverse the Horizontal mirror img (original)

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0],
       [1, 2, 3, 4, 5]])

In [32]:
c[::+1,::-1]      # it is reverse vertical mirror img (original)

array([[5, 4, 3, 2, 1],
       [0, 8, 6, 4, 2],
       [9, 7, 5, 3, 1]])

In [33]:
c[::-1,::-1]     # First it reverse Horizontal and again it reverse vertical img (original)  -- or --
                 # First it reverse Vertical and again it reverse Horizontal img (original)

array([[9, 7, 5, 3, 1],
       [0, 8, 6, 4, 2],
       [5, 4, 3, 2, 1]])

In [34]:
c[::+1]      # It is Also as same as the Orginal

array([[1, 2, 3, 4, 5],
       [2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

#### or

In [35]:
c[::+1,::+1]      # It is same as the Original

array([[1, 2, 3, 4, 5],
       [2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

### ex 2

In [36]:
b = [[11,22,33,44,55],
     [66,77,88,99,0]]  
d =  np.array(b)
d


array([[11, 22, 33, 44, 55],
       [66, 77, 88, 99,  0]])

In [37]:
d[::-1]          

array([[66, 77, 88, 99,  0],
       [11, 22, 33, 44, 55]])

In [38]:
d[ ::-1 , ::-1]

array([[ 0, 99, 88, 77, 66],
       [55, 44, 33, 22, 11]])