#  Specific Element Extraction





In [12]:
import numpy as np

In [23]:
    #  0   1   2   3   4
    #  -5  -4  -3  -2  -1
    
a = [[ 2 , 4 , 6 , 8 , 0 ],   
     [ 1 , 3 , 5 , 7 , 9 ]]
b = np.array(a) 
b

array([[2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

In [27]:
b[: , -1]

array([0, 9])

In [32]:
b[-1 , :]

array([1, 3, 5, 7, 9])

In [16]:
b[: , :]

array([[2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

In [17]:
b[-1,-1]

9

In [18]:
b[-2 , -3]

6

In [19]:
b[0 ,:]

# or

b[-2 , :]

array([2, 4, 6, 8, 0])

### slicing

In [35]:
b[: , 1:3]   # 1:3 = column(1  2)      ## slicing

array([[4, 6],
       [3, 5]])

In [21]:
b[:, -5:-2]   # don't write -2:-5 , write only in increase order

array([[2, 4, 6],
       [1, 3, 5]])

In [22]:
# or
b[:,0:3]

array([[2, 4, 6],
       [1, 3, 5]])