# Basic Statistics 

In [117]:
import numpy as np

In [118]:
m = [23,64,51,63,18,4] , [2,41,5,6,8,4]
n = np.array(m)
n

array([[23, 64, 51, 63, 18,  4],
       [ 2, 41,  5,  6,  8,  4]])

In [160]:
n1 = np.max(n)  # Recommended
n1

# or

# n1 = n.min()
# n1

64

In [152]:
n2 = np.min(n)  # Recommended
n2

# or

# n2 = n.min()
# n2

2

In [130]:
n3 = np.sum(n)  # Recommended
n3

# or

# n3 = n.sum()
# n3

289

#  Average

In [131]:
import numpy as np
o = [[2,3,4,6],
     [3,6,4,1]]
p = np.array(o)
print(p)

q = np.average(p)
q

[[2 3 4 6]
 [3 6 4 1]]


3.625

# Variance

In [123]:
h = [[2,3,4,6],
     [3,6,4,1]]
k = np.array(h) 
k

k = np.var(k)
k

2.734375

# Mean

In [124]:
import numpy as np

In [142]:
c = [1,2,3,4,5,6,7,8]       # sum of all values / total no of values
d = np.array(c)
d

d = np.mean(d)
d

4.5

# Median 

In [126]:
import numpy as np

In [127]:
# ex 1
a = [1,2,3,4,5,6,7,8,9 ,9]     # add middle two values / 2
b = np.array(a)
b

b = np.median(b)
b

5.5

In [137]:
# ex 2
import numpy as np

speed = [99,86,87,88,111,86,103,87,94,78,77]# it will sorting , that means increase the number and then it take middle value

x = np.array(speed)

print(x)

x = np.mo(x)
x

[ 99  86  87  88 111  86 103  87  94  78  77]


87.0

# Mode

In [150]:
from scipy import stats                   # for mode it is different
e = [11,22,77,33,99,33,24,22,33]
f = np.array(e)
f

f1 = stats.mode(f)
f1

ModeResult(mode=33, count=3)