# Arange 

In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1,10,3)

array([1, 4, 7])

In [6]:
np.arange(10,0,-1)         # for Descending order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Linespace 

In [7]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [8]:
np.linspace(2,10,5)                  # it give 5 values

array([ 2.,  4.,  6.,  8., 10.])

In [9]:
np.linspace(1,10,3)                  # it give 3 values

array([ 1. ,  5.5, 10. ])

In [10]:
np.linspace(1,10,4)                 # it give 4 values

array([ 1.,  4.,  7., 10.])

# Zeros

In [24]:
a = [2,3]     # @ rows and 3 Columns

a = np.array(a)
a

array([2, 3])

In [23]:
np.zeros(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros([2,3,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [25]:
b = [1,5,2,7]
b= np.array(b)
b

array([1, 5, 2, 7])

In [26]:
np.zeros(b)

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]]])