In [2]:
import numpy as np

## In Arrays

In [15]:
a = [[1,4,5,2,2,5],
     [4,4,1,7,4,5]]
a

a= np.array(a)
a

array([[1, 4, 5, 2, 2, 5],
       [4, 4, 1, 7, 4, 5]])

### Display Unique Values

In [16]:
u = np.unique(a)   
u

array([1, 2, 4, 5, 7])

### Length of Unique Values

In [17]:
l = len(np.unique(a))
l

5

###  Count the Unique values

In [18]:
c =np.unique(a,return_counts = True)
c

(array([1, 2, 4, 5, 7]), array([2, 2, 4, 3, 1], dtype=int64))

## In DataFrame

In [38]:
import pandas as pd

data1 = {'color': ['red', 'blue', 'green', 'red', 'blue'],
         'age' :[23 , np.NaN,12,54,23]}              

df = pd.DataFrame(data1) 
df

# Good clarification in = "17. ML - Categorical Data .ipynb"

# ********* Don't use unique for entire dataframe(df) , use individual(df['age'])
# ******* But using value_count we can use entire dataframe (df) and also individual(df['age'])

color   age
0    red  23.0
1   blue   NaN
2  green  12.0
3    red  54.0
4   blue  23.0

In [30]:
c =np.unique(df['age'],return_counts = True)     # count the unique values
c

(array([12., 23., 54., nan]), array([1, 2, 1, 1], dtype=int64))

In [33]:
l = len(np.unique(df['age']))                # len of the unique values
l

4

In [34]:
a = np.unique(df['age'])        # Display Unique values
a

array([12., 23., 54., nan])