In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\\ML\\26. ML - Regression Trees Data.csv")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

###  We Need to check is there any na values

In [3]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [4]:
x = df[['AT' , 'V', 'AP' ,'RH']]
x.head()

AT      V       AP     RH
0  14.96  41.76  1024.07  73.17
1  25.18  62.96  1020.04  59.08
2   5.11  39.40  1012.16  92.14
3  20.86  57.32  1010.24  76.64
4  10.82  37.50  1009.23  96.62

In [5]:
y = df[['PE']]
y.head()

PE
0  463.26
1  444.37
2  488.56
3  446.48
4  473.90

#  need to convert 1D array to 2D array

In [6]:
x = np.array(x)
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
y = np.array(y)
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2 , random_state=0)

In [10]:
x_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
ss = StandardScaler()

In [13]:
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)
# y_train = ss.fit_transform(y_train)  # First check without scalling (y , y_train , y_test) , if we got less accuarcy means then try this...
# y_test = ss.transform(y_test)

In [14]:
x_train

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [15]:
x_test

array([[ 1.20924389,  1.84743445, -0.61878043, -0.28968211],
       [-0.29401214, -0.39528045,  1.39211729,  0.76937061],
       [-0.64629575, -0.88607065,  1.00508258,  1.77019599],
       ...,
       [-0.99857936, -0.74629361,  1.76737267,  1.02146078],
       [ 1.02368993, -0.50992904, -1.64526378, -0.96443434],
       [-0.32090402, -1.13342892, -1.03442205,  0.0651622 ]])

In [16]:
y_test

array([[431.23],
       [460.01],
       [461.14],
       ...,
       [473.26],
       [438.  ],
       [463.28]])

In [17]:
from sklearn.tree import DecisionTreeRegressor

In [18]:
dt = DecisionTreeRegressor()

In [19]:
dt.fit(x_train , y_train)

DecisionTreeRegressor()

In [20]:
y_pred = dt.predict(x_test)
y_pred

array([429.06, 459.59, 460.06, ..., 471.46, 437.76, 462.55])

## r2_score is used to check the program is correct 

In [21]:
from sklearn.metrics import r2_score

### The output near to '1' means the program is good , if it near to '0' the code is bad 

In [22]:
r2_score(y_test , y_pred )

0.9221302949413777

In [23]:
y_pred1 = dt.predict([[ -0.29401214, -0.39528045,  1.39211729,  0.76937061]])
# y_pred1 = sc.inverse_transform(y_pred1)      # This will use only if we make scaling for - [y , y_train , y_test]
y_pred1

array([459.59])