#                                              Array

In [23]:
import numpy as np
a = (1,2,3,4,5)
b = np.array(a)
print(b)
b

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [60]:

a1 = [1,2,3,4,5]
b1 = np.array(a1)
print(b1)
b1

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

# Type

In [35]:
type(a)

list

In [31]:
type(b)

numpy.ndarray

In [30]:
type(a1)

list

In [29]:
type(b1)

numpy.ndarray

# convert list to array

###  In list we cannot edit the details , but in array we can edit the details

In [71]:
c = [1,3,4,5,6,8]     # it is an list 
d = np.array(c)       # it is an array
d

array([1, 3, 4, 5, 6, 8])

In [73]:
c +  1       # it shows an error

TypeError: can only concatenate list (not "int") to list

In [72]:
d + 1

array([2, 4, 5, 6, 7, 9])

# float array

### array to float

In [89]:
m = [ [1,25,4,5,67] ,
     [3,55,7,95,0] ]
n = np.array(m)
n

array([[ 1, 25,  4,  5, 67],
       [ 3, 55,  7, 95,  0]])

In [86]:
n = np.array(m , dtype ='float')
n

array([[ 1., 25.,  4.,  5., 67.],
       [ 3., 55.,  7., 95.,  0.]])

### float to int

In [98]:
x = n.astype('int')
x

array([[ 1, 25,  4,  5, 67],
       [ 3, 55,  7, 95,  0]])

 # Boolean array

### array to boolean

In [95]:
o = [ [1,25,4,5,67] ,
     [3,55,7,95,0] ]
p = np.array(o)
p

array([[ 1, 25,  4,  5, 67],
       [ 3, 55,  7, 95,  0]])

In [96]:
q = np.array(p , dtype = 'bool')             # in bool 0 = false , any other number = 1
q

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

### bool to int

In [99]:
y = q.astype('int')
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0]])