# Reversing  Rows and Columns

In [45]:
import numpy as np

### ex 1

In [29]:
a = [[1,2,3,4,5],
      [2,4,6,8,0],
      [1,3,5,7,9]] 
     
c =  np.array(a)        
c 

array([[1, 2, 3, 4, 5],
       [2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

In [46]:
c[::-1]           # it is only reverse the row

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0],
       [1, 2, 3, 4, 5]])

In [49]:
c[::-1,::-1]      # it is reverse the row x column

array([[9, 7, 5, 3, 1],
       [0, 8, 6, 4, 2],
       [5, 4, 3, 2, 1]])

### ex 2

In [34]:
b = [[11,22,33,44,55],
     [66,77,88,99,0]]  
d =  np.array(b)
d


array([[11, 22, 33, 44, 55],
       [66, 77, 88, 99,  0]])

In [47]:
d[::-1]          

array([[66, 77, 88, 99,  0],
       [11, 22, 33, 44, 55]])

In [53]:
d[ ::-1 , ::-1]

array([[ 0, 99, 88, 77, 66],
       [55, 44, 33, 22, 11]])