# Reshaping 

In [2]:
import numpy as np

In [4]:
a = [[1,2,3,4,5],
     [6,7,8,9,0]]
b = np.array(a)
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [6]:
b.shape   

(2, 5)

In [9]:
b.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [16]:
b.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [14]:
b.reshape(1,10)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [15]:
b.reshape(10,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]])

#  Flattening 

In [27]:
c = [[1,3,5,7,9],
     [3,4,5,6,7],
     [2,4,6,8,0]]
d = np.array(c)
d

array([[1, 3, 5, 7, 9],
       [3, 4, 5, 6, 7],
       [2, 4, 6, 8, 0]])

In [29]:
f = d.flatten()      # flatten is used to combile all brackets into a single bracket line
f

array([1, 3, 5, 7, 9, 3, 4, 5, 6, 7, 2, 4, 6, 8, 0])

In [33]:
d.ndim

2

In [34]:
f.ndim

1